services:
  dbpostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodarch
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d foodarch"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - foodarch
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    networks:
      - foodarch
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://dbpostgres:5432/foodarch
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 120s
    depends_on:
      - dbpostgres
      - nginx
    networks:
      - foodarch

networks:
  foodarch:
    driver: bridge

volumes:
  db_data:
