name: Docker Image CI

on:
  push:
    branches:
      - main  # ou a branch de sua escolha
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fiap_foodarch:1.0.0 -t ${{ secrets.DOCKERHUB_USERNAME }}/fiap_foodarch:latest .
    
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fiap_foodarch:1.0.0
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fiap_foodarch:latest
